version: "3.8"
services:
  nv-cubb:
    container_name: nv-cubb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    network_mode: host
    shm_size: 4096m
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - /lib/modules:/lib/modules
      - /dev/hugepages:/dev/hugepages
      - /usr/src:/usr/src
      - ./aerial_l1_entrypoint.sh:/opt/nvidia/cuBB/aerial_l1_entrypoint.sh
      - /var/log/aerial:/var/log/aerial
      - /home/aerial/openairinterface5g/cmake_targets/share:/opt/cuBB/share   #ethos
      - ./run_controller.sh:/opt/nvidia/cuBB/run_controller.sh          #ethos
    userns_mode: host
    ipc: "shareable"
    image: cubb-build:23-4
    environment:
      - cuBB_SDK=/opt/nvidia/cuBB
    # command: bash -c " sudo rm -rf /tmp/phy.log && sudo chmod +x /opt/nvidia/cuBB/aerial_l1_entrypoint.sh && /opt/nvidia/cuBB/aerial_l1_entrypoint.sh"      #ethos
    # command: bash -c " sudo rm -rf /tmp/phy.log && sudo chmod +x /opt/nvidia/cuBB/run_controller.sh && /opt/nvidia/cuBB/run_controller.sh | tee nv_cuBB.log"     #ethos
    command: bash -c "sleep infinity"
    healthcheck:
      test: ["CMD-SHELL",'grep -q "L1 is ready!" /tmp/phy.log && echo 0 || echo 1']
      interval: 20s
      timeout: 5s
      retries: 5
  oai-gnb-aerial:
#    cpuset: "13-20"
    image: oai-gnb-aerial-ethos:dev
    depends_on:
      nv-cubb:
        condition: service_healthy
    privileged: true
    ipc: "container:nv-cubb"
    environment:
      USE_ADDITIONAL_OPTIONS: --log_config.global_log_options level,nocolor,time
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    network_mode: host
    shm_size: 4096m
    stdin_open: true
    tty: true
    volumes:
      - /home/aerial/ethos-dev/ethos-automation/ethos-aerial-yaml/ethos_conf/ethos-gnb-vnf.sa.band78.273prb.aerial.conf:/opt/oai-gnb/etc/gnb.conf
      - /var/log/aerial:/var/log/aerial
      # Use this for NVIDIA-RU1 radios
      - ../ethos_conf/ethos-gnb-vnf.sa.band78.273prb.aerial.conf:/opt/oai-gnb/etc/gnb-1.conf
      # Use this for CBRS radios
      - ../ethos_conf/ethos-gnb-vnf.sa.cbrs.aerial.conf:/opt/oai-gnb/etc/gnb-2.conf
      - ../../../ethos-oai-dev-docker/oai-ethos-dev-patches-Gigabyte:/opt/oai-ethos-dev-patches-Gigabyte  # ethos RL patches
      - ./gnb_apply_patch_build.sh:/opt/oai-gnb/gnb_apply_patch_build.sh    # ethos RL building script
#      - /home/aerial/openairinterface5g:/opt/openairinterface5g     #zongshen compose 
    # command: bash -c "chmod +x /opt/oai-gnb/etc/ethos_conf/*.sh && /opt/oai-gnb/etc/ethos_conf/ethos-change-dlmaxmcs.sh && 
                      # chrt -f 99 /opt/oai-gnb/bin/nr-softmodem -O /opt/oai-gnb/etc/ethos_conf/ethos-gnb-vnf.sa.band78.273prb.aerial.conf| ts | tee oai.log"     #ethos
    # command: bash -c "chrt -f 99 /opt/oai-gnb/bin/nr-softmodem -O /opt/oai-gnb/etc/gnb.conf | ts | tee oai.log"     #ethos
    command: bash -c "sleep infinity"         #ethos
#   command: bash -c "/opt/oai-gnb/bin/nr-softmodem -O /opt/oai-gnb/etc/gnb.conf | ts | tee /var/log/aerial/oai.log"
    container_name: oai-gnb-aerial
    healthcheck:
      test: /bin/bash -c "ps aux | grep -v grep | grep -c softmodem"
      interval: 10s
      timeout: 5s
      retries: 5
